"""Helpers for scaffolding new YAML report definitions.

Used by ``python main.py --scaffold --name my_report`` to drop a starter
``config/reports/my_report.yaml`` file that the user can fill in.
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

from app.utils.logger import get_logger

logger = get_logger(__name__)


_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_REPORTS_DIR = _REPO_ROOT / "config" / "reports"


def _slug(value: str) -> str:
    """Lowercase alphanumeric + underscore slug for filenames/keys."""

    return re.sub(r"[^a-z0-9_]+", "_", value.strip().lower()).strip("_")


def scaffold_yaml_report(name: str, overwrite: bool = False) -> Path:
    """Write a starter YAML file under ``config/reports/`` and return its path.

    Args:
        name: Human-friendly report name. Will be slugified for the filename.
        overwrite: If False (default) and the file exists, raise ``FileExistsError``.

    Raises:
        FileExistsError: If the target already exists and ``overwrite`` is False.
    """

    slug = _slug(name)
    if not slug:
        raise ValueError(f"Could not derive a slug from name={name!r}")

    target = _REPORTS_DIR / f"{slug}.yaml"
    target.parent.mkdir(parents=True, exist_ok=True)

    if target.exists() and not overwrite:
        raise FileExistsError(f"{target} already exists; pass overwrite=True to replace.")

    payload = {
        "name": slug,
        "metadata_dataset_file_name": f"{slug}_metadata",
        "cards": [
            {
                "dashboard": "Replace With Dashboard Name",
                "card": "Replace With Card Name",
                "viz_type": "Single Value",
            }
        ],
        "destinations": [
            {"type": "slack", "channel_name": "your-slack-channel"},
        ],
        "schedule": "0 14 * * *",
    }

    with target.open("w", encoding="utf-8") as fh:
        fh.write("# Auto-generated by `python main.py --scaffold`. Edit me!\n")
        yaml.safe_dump(payload, fh, sort_keys=False, default_flow_style=False)

    logger.info("Scaffolded new report at %s", target)
    return target


def add_card_to_report(
    report_name: str,
    dashboard: str,
    card: str,
    viz_type: str,
) -> Path:
    """Append a new card entry to an existing ``config/reports/<name>.yaml``.

    Returns the path of the file that was updated.

    Raises:
        FileNotFoundError: If the named report does not exist.
    """

    slug = _slug(report_name)
    target = _REPORTS_DIR / f"{slug}.yaml"
    if not target.exists():
        raise FileNotFoundError(f"No report found at {target}")

    with target.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}

    data.setdefault("cards", []).append(
        {"dashboard": dashboard, "card": card, "viz_type": viz_type}
    )

    with target.open("w", encoding="utf-8") as fh:
        yaml.safe_dump(data, fh, sort_keys=False, default_flow_style=False)

    logger.info("Added card to %s: [%s | %s | %s]", target, dashboard, card, viz_type)
    return target
